name: 🐛 Bug Report
description: Report a bug encountered in the application
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: Clearly describe what’s not working.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
    validations:
      required: false
