name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      SECRET_KEY: "123456789"
      ENV: "production"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Créer le fichier .env
        run: |
          echo "SECRET_KEY=${SECRET_KEY}" > .env
          echo "ENV=${ENV}" >> .env
          echo 'FIREBASE_SERVICE_ACCOUNT<<EOF' >> .env
          echo "${FIREBASE_SERVICE_ACCOUNT}" >> .env
          echo 'EOF' >> .env

      - name: Debug .env
        run: cat .env

      - name: Lancer Flask
        run: python app.py --help
